name: Deliver Tokens To Consumer 

on:
  push:
    paths:	
      - 'build/**'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_react_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Application
      uses: andstor/copycat-action@v3
      with:
        access-token: ${{ secrets.API_TOKEN_GITHUB }}
        src_branch: main
        src_path: build/js/_variables.js
        dst_owner: LegendT
        dst_repo_name: consume-style-dictionary-github-actions
        dst_branch: main
        dst_path: tokens/_variables.js
        commit_message: Update design tokens
